name: actions-includes
description: 'Allow actions to include other actions.'
inputs:
  workflow:
    description: 'Workflow file to check include expansion'
    required: true
runs:
  using: "composite"

  steps:
  - shell: bash
    run: |
      python3 "${{ github.action_path }}/check_workflow.py" "${{ inputs.workflow }}"
